### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by maxwondercorn** [djsegal/ember-browser-checker#6]
@djsegal Would you be supportive of a major PR to upgrade to Ember 3.* and possibly using the [bowser](https://www.npmjs.com/package/bowser) library for browser detection?

The addon is still used by a large number of projects and it provides needed functionality. I see you have not done much with Ember for several years, so if you have no interest I could update the addon if you add me as a maintainer.

Another option would be moving the addon to [adopter-ember-addons](https://github.com/adopted-ember-addons/program-guidelines) where it would get long term community support

**Comment by djsegal** [comment]
Added you as a collaborator. Thanks for keeping the project going!

**Comment by maxwondercorn** [comment]
Thanks.  I will start working on it this week
