### ISSUE TITLE
Delete "app/styles/app.scss"

### ISSUE THREAD

**Issue by bertdeblock** [djsegal/ember-browser-checker#9]
Don't think this file needs to be part of the `app` folder?
It imports `ember-paper` which is only needed for the dummy app and [that import is already done here](https://github.com/djsegal/ember-browser-checker/blob/master/tests/dummy/app/styles/app.scss#L1).

**Comment by maxwondercorn** [comment]
The import is needed to define the $color-blue-gray variable

**Comment by bertdeblock** [comment]
But why in the `app` folder? `ember-paper` is a dev dependency so the import doesn't need to be published or available to the host app I'd think? Everything works fine locally without it as well.

**Comment by maxwondercorn** [comment]
@bertdeblock You are correct the app.scss file is not needed.  I misread what you were asking and thought you were talking about the import in the dummy app 🤦   I didn't realize there was a styles directory in app.

Fixed and published
